// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(JaliriContext))]
    [Migration("20240421185829_first-migration")]
    partial class firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entity.Concrete.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Genders")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genders = "Erkek"
                        },
                        new
                        {
                            Id = 2,
                            Genders = "Kadın"
                        },
                        new
                        {
                            Id = 3,
                            Genders = "Çocuk"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BarcodeId")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int?>("ColorId")
                        .HasColumnType("integer");

                    b.Property<int>("GenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuantityPerUnit")
                        .HasColumnType("integer");

                    b.Property<int?>("SizeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BarcodeId");

                    b.HasIndex("BrandId");

                    b.HasIndex("ColorId");

                    b.HasIndex("GenderId");

                    b.HasIndex("SizeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarcodeId = 1,
                            BrandId = 1,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1070),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1070),
                            ProductDescription = "",
                            ProductName = "Run Falcon 3",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 1803.95m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 2,
                            BarcodeId = 1,
                            BrandId = 1,
                            ColorId = 2,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1076),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1076),
                            ProductDescription = "",
                            ProductName = "Hoops 3 Low",
                            QuantityPerUnit = 1,
                            SizeId = 17,
                            UnitPrice = 1819.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 3,
                            BarcodeId = 1,
                            BrandId = 1,
                            ColorId = 3,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1080),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1080),
                            ProductDescription = "",
                            ProductName = "Ground Court Base",
                            QuantityPerUnit = 1,
                            SizeId = 11,
                            UnitPrice = 1689.95m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 4,
                            BarcodeId = 1,
                            BrandId = 1,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1083),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1083),
                            ProductDescription = "",
                            ProductName = "Samoa Spor Ayakkabı",
                            QuantityPerUnit = 1,
                            SizeId = 20,
                            UnitPrice = 2099.25m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 5,
                            BarcodeId = 1,
                            BrandId = 1,
                            ColorId = 1,
                            GenderId = 3,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1086),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1086),
                            ProductDescription = "",
                            ProductName = "Superstar Co Erkek Spor",
                            QuantityPerUnit = 1,
                            SizeId = 10,
                            UnitPrice = 3179.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 6,
                            BarcodeId = 2,
                            BrandId = 2,
                            ColorId = 3,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1090),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1090),
                            ProductDescription = "",
                            ProductName = "Downshifter",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 2417.85m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 7,
                            BarcodeId = 2,
                            BrandId = 2,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1095),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1095),
                            ProductDescription = "",
                            ProductName = "Air Force",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 1749m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 8,
                            BarcodeId = 2,
                            BrandId = 2,
                            ColorId = 5,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1098),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1098),
                            ProductDescription = "",
                            ProductName = "Halı Saha Legend 10",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 2335.26m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 9,
                            BarcodeId = 2,
                            BrandId = 2,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1101),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1102),
                            ProductDescription = "",
                            ProductName = "Air Max Alpha Trainer",
                            QuantityPerUnit = 1,
                            SizeId = 15,
                            UnitPrice = 3299m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 10,
                            BarcodeId = 2,
                            BrandId = 2,
                            ColorId = 10,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1105),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1105),
                            ProductDescription = "",
                            ProductName = "Air Monarch Iv 415445-102 Spor Ayakkabı",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 2417.85m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 11,
                            BarcodeId = 3,
                            BrandId = 3,
                            ColorId = 8,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1108),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1108),
                            ProductDescription = "",
                            ProductName = "Sneaker Spor Ayakkabı",
                            QuantityPerUnit = 1,
                            SizeId = 20,
                            UnitPrice = 699.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 12,
                            BarcodeId = 3,
                            BrandId = 3,
                            ColorId = 5,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1111),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1111),
                            ProductDescription = "",
                            ProductName = "Abena Sneaker Spor Ayakkabı",
                            QuantityPerUnit = 1,
                            SizeId = 21,
                            UnitPrice = 574.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 13,
                            BarcodeId = 3,
                            BrandId = 3,
                            ColorId = 6,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1116),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1116),
                            ProductDescription = "",
                            ProductName = "Thermo Outdoor",
                            QuantityPerUnit = 1,
                            SizeId = 11,
                            UnitPrice = 899.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 14,
                            BarcodeId = 3,
                            BrandId = 3,
                            ColorId = 3,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1118),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1119),
                            ProductDescription = "",
                            ProductName = "Slezenger Maroon | Sneaker",
                            QuantityPerUnit = 1,
                            SizeId = 13,
                            UnitPrice = 499.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 15,
                            BarcodeId = 3,
                            BrandId = 3,
                            ColorId = 7,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1121),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1122),
                            ProductDescription = "",
                            ProductName = "Slezenger Olivia | Sneaker",
                            QuantityPerUnit = 1,
                            SizeId = 14,
                            UnitPrice = 889.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 16,
                            BarcodeId = 4,
                            BrandId = 4,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1125),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1125),
                            ProductDescription = "",
                            ProductName = "New Balance 109",
                            QuantityPerUnit = 1,
                            SizeId = 18,
                            UnitPrice = 2399m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 17,
                            BarcodeId = 4,
                            BrandId = 4,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1128),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1128),
                            ProductDescription = "",
                            ProductName = "New Balance 530 Lifestyle",
                            QuantityPerUnit = 1,
                            SizeId = 21,
                            UnitPrice = 7850m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 18,
                            BarcodeId = 4,
                            BrandId = 4,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1132),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1132),
                            ProductDescription = "",
                            ProductName = "New Balance 408 Lifestyle",
                            QuantityPerUnit = 1,
                            SizeId = 14,
                            UnitPrice = 2690.10m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 19,
                            BarcodeId = 4,
                            BrandId = 4,
                            ColorId = 7,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1134),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1135),
                            ProductDescription = "",
                            ProductName = "New Balance 9060 Grey Lilac",
                            QuantityPerUnit = 1,
                            SizeId = 13,
                            UnitPrice = 14999.10m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 20,
                            BarcodeId = 4,
                            BrandId = 4,
                            ColorId = 2,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1138),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1138),
                            ProductDescription = "",
                            ProductName = "New Balance 9060 Castlerock",
                            QuantityPerUnit = 1,
                            SizeId = 23,
                            UnitPrice = 13979.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 21,
                            BarcodeId = 5,
                            BrandId = 5,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1141),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1141),
                            ProductDescription = "",
                            ProductName = "Anzarun Lite",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 1785m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 22,
                            BarcodeId = 5,
                            BrandId = 5,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1144),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1144),
                            ProductDescription = "",
                            ProductName = "Roma Basic",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 1599m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 23,
                            BarcodeId = 5,
                            BrandId = 5,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1146),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1147),
                            ProductDescription = "",
                            ProductName = "Tech-Light",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 3263.88m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 24,
                            BarcodeId = 5,
                            BrandId = 5,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1150),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1150),
                            ProductDescription = "",
                            ProductName = "Caracal Sneaker",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 1875m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 25,
                            BarcodeId = 5,
                            BrandId = 5,
                            ColorId = 9,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1153),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1153),
                            ProductDescription = "",
                            ProductName = "Court Classic Vulc Retro-C",
                            QuantityPerUnit = 1,
                            SizeId = 17,
                            UnitPrice = 1871.95m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 26,
                            BarcodeId = 6,
                            BrandId = 6,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1156),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1156),
                            ProductDescription = "",
                            ProductName = "PORO 4FX",
                            QuantityPerUnit = 1,
                            SizeId = 11,
                            UnitPrice = 1871.95m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 27,
                            BarcodeId = 6,
                            BrandId = 6,
                            ColorId = 1,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1160),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1160),
                            ProductDescription = "",
                            ProductName = "EYON 4FX",
                            QuantityPerUnit = 1,
                            SizeId = 14,
                            UnitPrice = 749.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 28,
                            BarcodeId = 6,
                            BrandId = 6,
                            ColorId = 7,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1179),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1179),
                            ProductDescription = "",
                            ProductName = "CAYDE 2PR",
                            QuantityPerUnit = 1,
                            SizeId = 11,
                            UnitPrice = 621m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 29,
                            BarcodeId = 6,
                            BrandId = 6,
                            ColorId = 1,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1182),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1182),
                            ProductDescription = "",
                            ProductName = "AXION TX",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 1199.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 30,
                            BarcodeId = 6,
                            BrandId = 6,
                            ColorId = 10,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1185),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1185),
                            ProductDescription = "",
                            ProductName = "SOLIDA",
                            QuantityPerUnit = 1,
                            SizeId = 13,
                            UnitPrice = 799.88m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 31,
                            BarcodeId = 7,
                            BrandId = 7,
                            ColorId = 10,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1189),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1189),
                            ProductDescription = "",
                            ProductName = "Hata Breatha Kadın",
                            QuantityPerUnit = 1,
                            SizeId = 13,
                            UnitPrice = 7199.88m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 32,
                            BarcodeId = 7,
                            BrandId = 7,
                            ColorId = 9,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1192),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1192),
                            ProductDescription = "",
                            ProductName = "Max Outdry",
                            QuantityPerUnit = 1,
                            SizeId = 17,
                            UnitPrice = 4299.88m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 33,
                            BarcodeId = 7,
                            BrandId = 7,
                            ColorId = 4,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1195),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1195),
                            ProductDescription = "",
                            ProductName = "Creastwood WaterProof",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 4299.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 34,
                            BarcodeId = 7,
                            BrandId = 7,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1200),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1200),
                            ProductDescription = "",
                            ProductName = "Firecamp Waterproof",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 3679.98m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 35,
                            BarcodeId = 7,
                            BrandId = 7,
                            ColorId = 4,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1203),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1203),
                            ProductDescription = "",
                            ProductName = "Castback",
                            QuantityPerUnit = 1,
                            SizeId = 13,
                            UnitPrice = 2999.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 36,
                            BarcodeId = 8,
                            BrandId = 8,
                            ColorId = 8,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1206),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1206),
                            ProductDescription = "",
                            ProductName = "Chuck Taylor All Star",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 2469m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 37,
                            BarcodeId = 8,
                            BrandId = 8,
                            ColorId = 2,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1209),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1209),
                            ProductDescription = "",
                            ProductName = "Converse Soft White",
                            QuantityPerUnit = 1,
                            SizeId = 11,
                            UnitPrice = 2367m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 38,
                            BarcodeId = 8,
                            BrandId = 8,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1212),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1212),
                            ProductDescription = "",
                            ProductName = "Lift Platform",
                            QuantityPerUnit = 1,
                            SizeId = 18,
                            UnitPrice = 3099m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 39,
                            BarcodeId = 8,
                            BrandId = 8,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1215),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1215),
                            ProductDescription = "",
                            ProductName = "All Star Lift Boy",
                            QuantityPerUnit = 1,
                            SizeId = 18,
                            UnitPrice = 2499m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 40,
                            BarcodeId = 8,
                            BrandId = 8,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1218),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1219),
                            ProductDescription = "",
                            ProductName = "Chuck Taylor All Star",
                            QuantityPerUnit = 1,
                            SizeId = 18,
                            UnitPrice = 1899m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 41,
                            BarcodeId = 9,
                            BrandId = 9,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1221),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1222),
                            ProductDescription = "",
                            ProductName = "Dockers 3fx Outdoor",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 1799m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 42,
                            BarcodeId = 9,
                            BrandId = 9,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1224),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1225),
                            ProductDescription = "",
                            ProductName = "Dockers 2pr Outdoor Asfalt",
                            QuantityPerUnit = 1,
                            SizeId = 20,
                            UnitPrice = 1255.79m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 43,
                            BarcodeId = 9,
                            BrandId = 9,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1227),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1227),
                            ProductDescription = "",
                            ProductName = "Dockers Comfort Casual Deri",
                            QuantityPerUnit = 1,
                            SizeId = 21,
                            UnitPrice = 2099.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 44,
                            BarcodeId = 9,
                            BrandId = 9,
                            ColorId = 8,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1230),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1230),
                            ProductDescription = "",
                            ProductName = "Dockers 1fx Outdoor Fit",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 899.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 45,
                            BarcodeId = 9,
                            BrandId = 9,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1233),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1233),
                            ProductDescription = "",
                            ProductName = "Dockers 3m Günlük",
                            QuantityPerUnit = 1,
                            SizeId = 18,
                            UnitPrice = 599.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 46,
                            BarcodeId = 10,
                            BrandId = 10,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1236),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1236),
                            ProductDescription = "",
                            ProductName = "Colaroda Black Deri",
                            QuantityPerUnit = 1,
                            SizeId = 17,
                            UnitPrice = 1973.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 47,
                            BarcodeId = 10,
                            BrandId = 10,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1238),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1239),
                            ProductDescription = "",
                            ProductName = "Toledo Vibram Kaymaz",
                            QuantityPerUnit = 1,
                            SizeId = 19,
                            UnitPrice = 3599.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 48,
                            BarcodeId = 10,
                            BrandId = 10,
                            ColorId = 10,
                            GenderId = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1241),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1241),
                            ProductDescription = "",
                            ProductName = "Riesco Sneaker",
                            QuantityPerUnit = 1,
                            SizeId = 12,
                            UnitPrice = 2059.90m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 49,
                            BarcodeId = 10,
                            BrandId = 10,
                            ColorId = 4,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1244),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1245),
                            ProductDescription = "",
                            ProductName = "Colaroda Expedition",
                            QuantityPerUnit = 1,
                            SizeId = 20,
                            UnitPrice = 4099.99m,
                            UnitsInStock = 10
                        },
                        new
                        {
                            Id = 50,
                            BarcodeId = 10,
                            BrandId = 10,
                            ColorId = 1,
                            GenderId = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1248),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1248),
                            ProductDescription = "",
                            ProductName = "Bot PICTON",
                            QuantityPerUnit = 1,
                            SizeId = 17,
                            UnitPrice = 2890.99m,
                            UnitsInStock = 10
                        });
                });

            modelBuilder.Entity("Entity.Concrete.ProductBarcode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProductBarcodes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "54698726110",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(830),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(830)
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "54698726111",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(837),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(837)
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "54698726112",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(840),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(841)
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "54698726114",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(843),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(843)
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "54698726115",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(846),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(847)
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "54698726116",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(850),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(851)
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "54698726117",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(854),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(854)
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "54698726118",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(857),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(857)
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "54698726119",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(860),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(860)
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "54698726121",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(863),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(863)
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "54698726122",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(866),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(866)
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "54698726123",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(869),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(869)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandCode")
                        .HasColumnType("text");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandCode")
                        .IsUnique();

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandCode = "A001",
                            BrandName = "Adidas",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(742),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(744)
                        },
                        new
                        {
                            Id = 2,
                            BrandCode = "N001",
                            BrandName = "Nike",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(765),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(765)
                        },
                        new
                        {
                            Id = 3,
                            BrandCode = "SL01",
                            BrandName = "Slezenger",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(769),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(769)
                        },
                        new
                        {
                            Id = 4,
                            BrandCode = "NB01",
                            BrandName = "New Balance",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(772),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(772)
                        },
                        new
                        {
                            Id = 5,
                            BrandCode = "PM01",
                            BrandName = "Puma",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(775),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(775)
                        },
                        new
                        {
                            Id = 6,
                            BrandCode = "KX01",
                            BrandName = "Kinetix",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(779),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(779)
                        },
                        new
                        {
                            Id = 7,
                            BrandCode = "CL01",
                            BrandName = "Columbia",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(781),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(782)
                        },
                        new
                        {
                            Id = 8,
                            BrandCode = "CRS01",
                            BrandName = "Converse",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(784),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(784)
                        },
                        new
                        {
                            Id = 9,
                            BrandCode = "DK01",
                            BrandName = "Dockers",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(810),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(811)
                        },
                        new
                        {
                            Id = 10,
                            BrandCode = "CP01",
                            BrandName = "CaterPillar",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(815),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(815)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.ProductColor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasColumnType("text");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ColorCode")
                        .IsUnique();

                    b.ToTable("ProductColors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "S001",
                            ColorName = "Siyah",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(966),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(966)
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "B001",
                            ColorName = "Beyaz",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(972),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(972)
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "K001",
                            ColorName = "Kırmızı",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(975),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(975)
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "SA01",
                            ColorName = "Sarı",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(978),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(978)
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "T001",
                            ColorName = "Turuncu",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1003),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1003)
                        },
                        new
                        {
                            Id = 6,
                            ColorCode = "ZY01",
                            ColorName = "Yeşil",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1007),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1007)
                        },
                        new
                        {
                            Id = 7,
                            ColorCode = "L001",
                            ColorName = "Mor",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1010),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1010)
                        },
                        new
                        {
                            Id = 8,
                            ColorCode = "MU01",
                            ColorName = "Lacivert",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1012),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1013)
                        },
                        new
                        {
                            Id = 9,
                            ColorCode = "PM01",
                            ColorName = "Mavi",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1016),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1016)
                        },
                        new
                        {
                            Id = 10,
                            ColorCode = "TP01",
                            ColorName = "Pembe",
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1019),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(1019)
                        });
                });

            modelBuilder.Entity("Entity.Concrete.ProductSize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastModifierDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductSizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(884),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(884),
                            Size = "XXS"
                        },
                        new
                        {
                            Id = 2,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(891),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(891),
                            Size = "XS"
                        },
                        new
                        {
                            Id = 3,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(894),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(894),
                            Size = "XS/S"
                        },
                        new
                        {
                            Id = 4,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(897),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(897),
                            Size = "S"
                        },
                        new
                        {
                            Id = 5,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(900),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(900),
                            Size = "S/M"
                        },
                        new
                        {
                            Id = 6,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(903),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(903),
                            Size = "M"
                        },
                        new
                        {
                            Id = 7,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(906),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(906),
                            Size = "L"
                        },
                        new
                        {
                            Id = 8,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(909),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(909),
                            Size = "L/XL"
                        },
                        new
                        {
                            Id = 9,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(911),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(912),
                            Size = "XL"
                        },
                        new
                        {
                            Id = 10,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(915),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(915),
                            Size = "34"
                        },
                        new
                        {
                            Id = 11,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(918),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(918),
                            Size = "35"
                        },
                        new
                        {
                            Id = 12,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(921),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(921),
                            Size = "36"
                        },
                        new
                        {
                            Id = 13,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(923),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(924),
                            Size = "37"
                        },
                        new
                        {
                            Id = 14,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(926),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(926),
                            Size = "38"
                        },
                        new
                        {
                            Id = 15,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(928),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(929),
                            Size = "39"
                        },
                        new
                        {
                            Id = 16,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(931),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(932),
                            Size = "40"
                        },
                        new
                        {
                            Id = 17,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(934),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(934),
                            Size = "41"
                        },
                        new
                        {
                            Id = 18,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(937),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(938),
                            Size = "42"
                        },
                        new
                        {
                            Id = 19,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(940),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(940),
                            Size = "43"
                        },
                        new
                        {
                            Id = 20,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(943),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(943),
                            Size = "44"
                        },
                        new
                        {
                            Id = 21,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(945),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(946),
                            Size = "45"
                        },
                        new
                        {
                            Id = 22,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(948),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(948),
                            Size = "46"
                        },
                        new
                        {
                            Id = 23,
                            InsertDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(951),
                            LastModifierDate = new DateTime(2024, 4, 21, 18, 58, 29, 48, DateTimeKind.Utc).AddTicks(951),
                            Size = "47"
                        });
                });

            modelBuilder.Entity("Entity.Concrete.Product", b =>
                {
                    b.HasOne("Entity.Concrete.ProductBarcode", "ProductBarcode")
                        .WithMany()
                        .HasForeignKey("BarcodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.ProductColor", "ProductColor")
                        .WithMany()
                        .HasForeignKey("ColorId");

                    b.HasOne("Entity.Concrete.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entity.Concrete.ProductSize", "ProductSize")
                        .WithMany()
                        .HasForeignKey("SizeId");

                    b.Navigation("Gender");

                    b.Navigation("ProductBarcode");

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductColor");

                    b.Navigation("ProductSize");
                });
#pragma warning restore 612, 618
        }
    }
}
